/* Replace with your SQL commands */
INSERT INTO restaurant (id, name, value) VALUES ( 303, "ドレッシング 500ml", 500);
INSERT INTO restaurant (id, name, value) VALUES ( 304, "オリーブオイル 500ml", 1200);
INSERT INTO restaurant (id, name, value) VALUES (1202, "小エビサラダ", 350);
INSERT INTO restaurant (id, name, value) VALUES (1209, "チキンサラダ", 350);
INSERT INTO restaurant (id, name, value) VALUES (1205, "わかめサラダ", 350);
INSERT INTO restaurant (id, name, value) VALUES (1208, "グリーンサラダ", 350);
INSERT INTO restaurant (id, name, value) VALUES (1207, "モッツアレラサラダ", 400);
INSERT INTO restaurant (id, name, value) VALUES (5101, "セットドリンクバー", 200);
INSERT INTO restaurant (id, name, value) VALUES (5102, "ドリンクバーキッズ", 100);
INSERT INTO restaurant (id, name, value) VALUES (5103, "単品", 300);
INSERT INTO restaurant (id, name, value) VALUES (1301, "コーンスープ", 150);
INSERT INTO restaurant (id, name, value) VALUES (1307, "玉ねぎのズッパ", 300);
INSERT INTO restaurant (id, name, value) VALUES (1305, "田舎のミネストローネ", 300);
INSERT INTO restaurant (id, name, value) VALUES (3108, "ミニフィセル", 150);
INSERT INTO restaurant (id, name, value) VALUES (3109, "ガーリックトースト", 200);
INSERT INTO restaurant (id, name, value) VALUES (3106, "プチフォッカ", 150);
INSERT INTO restaurant (id, name, value) VALUES (3104, "シナモンプチフォッカ", 200);
INSERT INTO restaurant (id, name, value) VALUES (3401, "グラスワイン 赤", 100);
INSERT INTO restaurant (id, name, value) VALUES (3402, "グラスワイン 白", 100);
INSERT INTO restaurant (id, name, value) VALUES (3403, "デカンタ 赤 250ml", 200);
INSERT INTO restaurant (id, name, value) VALUES (3404, "デカンタ 白 250ml", 200);
INSERT INTO restaurant (id, name, value) VALUES (3405, "デカンタ 赤 500ml", 400);
INSERT INTO restaurant (id, name, value) VALUES (3406, "デカンタ 白 500ml", 400);
INSERT INTO restaurant (id, name, value) VALUES (3407, "マグナム 赤", 1000);
INSERT INTO restaurant (id, name, value) VALUES (3408, "マグナム 白", 1000);
INSERT INTO restaurant (id, name, value) VALUES (3413, "ドンラファエロ", 1000);
INSERT INTO restaurant (id, name, value) VALUES (3416, "キャンディ", 1000);
INSERT INTO restaurant (id, name, value) VALUES (3412, "ランブルスコロゼ", 1000);
INSERT INTO restaurant (id, name, value) VALUES (3419, "キャンディ ルフィナ リゼルバ", 2000);
INSERT INTO restaurant (id, name, value) VALUES (3414, "ランブルスコセッコ", 1000);
INSERT INTO restaurant (id, name, value) VALUES (3415, "ベルデッキオ", 1000);
INSERT INTO restaurant (id, name, value) VALUES (3306, "グラッパ", 300);
INSERT INTO restaurant (id, name, value) VALUES (3301, "生 ジョッキ", 400);
INSERT INTO restaurant (id, name, value) VALUES (3302, "生 グラス", 300);
INSERT INTO restaurant (id, name, value) VALUES (3304, "レモンサワー", 350);
INSERT INTO restaurant (id, name, value) VALUES (3303, "ノンアルコール", 250);
INSERT INTO restaurant (id, name, value) VALUES (1423, "生ハムとモッツアレラ", 500);
INSERT INTO restaurant (id, name, value) VALUES (1422, "ハモン・セラーノ", 320);
INSERT INTO restaurant (id, name, value) VALUES (1414, "モッツアレラトマト", 280);
INSERT INTO restaurant (id, name, value) VALUES (1413, "にんじんサラダ", 200);
INSERT INTO restaurant (id, name, value) VALUES (1406, "小エビのカクテル", 280);
INSERT INTO restaurant (id, name, value) VALUES (1408, "蒸し鶏の香味ソース", 280);
INSERT INTO restaurant (id, name, value) VALUES (1425, "青豆の温サラダ", 200);
INSERT INTO restaurant (id, name, value) VALUES (1403, "ほうれん草のソテー", 200);
INSERT INTO restaurant (id, name, value) VALUES (1411, "アスパラガスの温サラダ", 300);
INSERT INTO restaurant (id, name, value) VALUES (1405, "エスカルゴのオーブン焼き", 400);
INSERT INTO restaurant (id, name, value) VALUES (1401, "辛味チキン", 300);
INSERT INTO restaurant (id, name, value) VALUES (1404, "ポップコーンシュリンプ", 300);
INSERT INTO restaurant (id, name, value) VALUES (1415, "カリッとポテト", 280);
INSERT INTO restaurant (id, name, value) VALUES (1407, "チョリソー", 400);
INSERT INTO restaurant (id, name, value) VALUES (1410, "ムール貝のガーリック焼き", 400);
INSERT INTO restaurant (id, name, value) VALUES (1402, "アロスティチーニ", 400);
INSERT INTO restaurant (id, name, value) VALUES (1452, "アロスティチーニ ダブルサイズ", 800);
INSERT INTO restaurant (id, name, value) VALUES (2201, "マルゲリータ", 400);
INSERT INTO restaurant (id, name, value) VALUES (2251, "マルゲリータ チーズ増し", 500);
INSERT INTO restaurant (id, name, value) VALUES (2202, "モッツアレラのピザ", 500);
INSERT INTO restaurant (id, name, value) VALUES (2252, "モッツアレラのピザ チーズ増し", 600);
INSERT INTO restaurant (id, name, value) VALUES (2204, "野菜ときのこのピザ", 400);
INSERT INTO restaurant (id, name, value) VALUES (2254, "野菜ときのこのピザ チーズ増し", 500);
INSERT INTO restaurant (id, name, value) VALUES (2208, "ソーセージピザ", 400);
INSERT INTO restaurant (id, name, value) VALUES (2258, "ソーセージピザ チーズ増し", 500);
INSERT INTO restaurant (id, name, value) VALUES (2206, "コーンピザ", 400);
INSERT INTO restaurant (id, name, value) VALUES (2256, "コーンピザ チーズ増し", 500);
INSERT INTO restaurant (id, name, value) VALUES (4106, "お子様ポテト", 100);
INSERT INTO restaurant (id, name, value) VALUES (4105, "お子様ポップコーンシュリンプ", 150);
INSERT INTO restaurant (id, name, value) VALUES (2109, "エビとたらこのグラタン", 430);
INSERT INTO restaurant (id, name, value) VALUES (2325, "ペンネアラビアータ", 430);
INSERT INTO restaurant (id, name, value) VALUES (2101, "ドリア", 300);
INSERT INTO restaurant (id, name, value) VALUES (2103, "半熟卵ドリア", 350);
INSERT INTO restaurant (id, name, value) VALUES (2108, "焼きチーズドリア", 350);
INSERT INTO restaurant (id, name, value) VALUES (2106, "たらことエビのドリア", 400);
INSERT INTO restaurant (id, name, value) VALUES (2109, "エビとたらこのグラタン", 430);
INSERT INTO restaurant (id, name, value) VALUES (2320, "小エビのたらこソース", 540);
INSERT INTO restaurant (id, name, value) VALUES (2315, "野菜のトマトスパゲッティ", 540);
INSERT INTO restaurant (id, name, value) VALUES (2310, "塩味ボンゴレ", 500);
INSERT INTO restaurant (id, name, value) VALUES (2328, "イカ墨入りセピアソース", 500);
INSERT INTO restaurant (id, name, value) VALUES (2321, "きのことほうれん草のクリームスパゲッティ", 600);
INSERT INTO restaurant (id, name, value) VALUES (2305, "カルボナーラ", 500);
INSERT INTO restaurant (id, name, value) VALUES (2306, "ミートソースボロニア風", 400);
INSERT INTO restaurant (id, name, value) VALUES (2316, "半熟卵 ミートソースボロニア風", 450);
INSERT INTO restaurant (id, name, value) VALUES (2301, "たらこソースシシリー", 400);
INSERT INTO restaurant (id, name, value) VALUES (2304, "パルマ風スパゲッティ", 400);
INSERT INTO restaurant (id, name, value) VALUES (2303, "ペペロンチーノ", 300);
INSERT INTO restaurant (id, name, value) VALUES (2317, "半熟卵 ペペロンチーノ", 350);
INSERT INTO restaurant (id, name, value) VALUES (4307, "粉チーズ", 100);
INSERT INTO restaurant (id, name, value) VALUES (4301, "半熟卵", 50);
INSERT INTO restaurant (id, name, value) VALUES (2406, "ハンバーグステーキ", 400);
INSERT INTO restaurant (id, name, value) VALUES (2407, "ディアボラ ハンバーグ", 500);
INSERT INTO restaurant (id, name, value) VALUES (2403, "イタリアンハンバーグ", 500);
INSERT INTO restaurant (id, name, value) VALUES (2418, "チョリソー ハンバーグ", 550);
INSERT INTO restaurant (id, name, value) VALUES (3101, "ライス", 150);
INSERT INTO restaurant (id, name, value) VALUES (3102, "Lライス", 200);
INSERT INTO restaurant (id, name, value) VALUES (3103, "Sライス", 100);
INSERT INTO restaurant (id, name, value) VALUES (2402, "若鳥のディアボラ", 500);
INSERT INTO restaurant (id, name, value) VALUES (2404, "柔らかチキンのチーズ焼き", 500);
INSERT INTO restaurant (id, name, value) VALUES (2413, "ラムと野菜のグリル", 870);
INSERT INTO restaurant (id, name, value) VALUES (4304, "野菜ペースト", 100);
INSERT INTO restaurant (id, name, value) VALUES (3206, "プリン(すぐに)", 250);
INSERT INTO restaurant (id, name, value) VALUES (3906, "プリン(後で)", 250);
INSERT INTO restaurant (id, name, value) VALUES (3201, "ティラミス(すぐに)", 300);
INSERT INTO restaurant (id, name, value) VALUES (3901, "ティラミス(後で)", 300);
INSERT INTO restaurant (id, name, value) VALUES (3212, "プリン ティラミス(すぐに)", 500);
INSERT INTO restaurant (id, name, value) VALUES (3912, "プリン ティラミス(後で)", 500);
INSERT INTO restaurant (id, name, value) VALUES (3205, "ジェラート(すぐに)", 250);
INSERT INTO restaurant (id, name, value) VALUES (3905, "ジェラート(後で)", 250);
INSERT INTO restaurant (id, name, value) VALUES (3213, "トリフアイス(すぐに)", 350);
INSERT INTO restaurant (id, name, value) VALUES (3913, "トリフアイス(後で)", 350);
INSERT INTO restaurant (id, name, value) VALUES (3207, "チョコケーキ(すぐに)", 300);
INSERT INTO restaurant (id, name, value) VALUES (3907, "チョコケーキ(後で)", 300);
INSERT INTO restaurant (id, name, value) VALUES (3215, "コーヒーゼリー ジェラート(すぐに)", 350);
INSERT INTO restaurant (id, name, value) VALUES (3915, "コーヒーゼリー ジェラート(後で)", 350);
INSERT INTO restaurant (id, name, value) VALUES (3204, "ジェラート シナモンプチフォッカ(すぐに)", 450);
INSERT INTO restaurant (id, name, value) VALUES (3904, "ジェラート シナモンプチフォッカ(後で)", 450);